'use client'
import React from 'react';
import { useParams } from 'next/navigation';
import PageHeading from "@/app/ui/PageHeading";
import Spacing from "@/app/ui/Spacing";
import Div from "@/app/ui/Div";
import portfolioData from "../../../../../data/portfolio";

export default function PrivacyPolicyPage() {
  const params = useParams();
  const portfolioId = params.portfolioDetailsId;
  const portfolioItem = portfolioData.find(item => item.id === portfolioId);

  const gameTitle = portfolioItem ? portfolioItem.title : 'Our Game';
  const privacyPolicy = portfolioItem?.privacyPolicy || {};
  const lastUpdated = privacyPolicy.lastUpdated || new Date().toLocaleDateString();
  const contactEmail = privacyPolicy.email || 'contact@ariversestudio.com';
  const collectsData = privacyPolicy.collectsData !== false; // Default to true if not specified
  const thirdPartyServices = privacyPolicy.thirdPartyServices || [];

  return (
    <>
      <PageHeading 
        title={`Privacy Policy for ${gameTitle}`}
        bgSrc='/images/service_hero_bg.jpeg'
        pageLinkText='PRIVACY POLICY'
      />
      <Spacing lg='150' md='80'/>
      <Div className="container">
        <Div className="row">
          <Div className="col-lg-10 offset-lg-1">
            <h2>Privacy Policy</h2>
            <p>Last updated: {lastUpdated}</p>
            
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            {collectsData ? (
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            ) : (
              <p>
                We do not collect or store any personal data from our users. By using the Service, You agree to the terms of this Privacy Policy.
              </p>
            )}

            <h3>Interpretation and Definitions</h3>
            <h4>Interpretation</h4>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h4>Definitions</h4>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Application</strong> refers to {gameTitle}, the software program provided by the Company.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Ariverse Studio.</li>
              <li><strong>Country</strong> refers to: Indonesia</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Application.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h3>Collecting and Using Your Personal Data</h3>
            
            {collectsData ? (
              <>
                <h4>Types of Data Collected</h4>
                
                <h5>Personal Data</h5>
                <p>
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul>
                  <li>Usage Data</li>
                </ul>

                <h5>Usage Data</h5>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>

                {thirdPartyServices.length > 0 && (
                  <>
                    <h4>Third-Party Services</h4>
                    <p>
                      We may employ third-party companies and individuals due to the following reasons:
                    </p>
                    <ul>
                      <li>To facilitate our Service;</li>
                      <li>To provide the Service on our behalf;</li>
                      <li>To perform Service-related services; or</li>
                      <li>To assist us in analyzing how our Service is used.</li>
                    </ul>
                    <p>
                      We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
                    </p>
                    <p>
                      The following third-party services are used in this Application:
                    </p>
                    <ul>
                      {thirdPartyServices.map((service, index) => (
                        <li key={index}>{service}</li>
                      ))}
                    </ul>
                  </>
                )}
              </>
            ) : (
              <p>
                We do not collect any personal data or usage data in this Application. The Application operates locally on your device and does not transmit any information to external servers.
              </p>
            )}

            <h3>Children's Privacy</h3>
            <p>
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>
            <p>
              If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
            </p>

            <h3>CCPA Privacy Rights (Do Not Sell My Personal Information)</h3>
            <p>Under the CCPA, among other rights, California consumers have the right to:</p>
            <ul>
              <li>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
              <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
              <li>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
            </ul>
            <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

            <h3>GDPR Data Protection Rights</h3>
            <p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
            <ul>
              <li><strong>The right to access</strong> – You have the right to request copies of your personal data. We may charge you a small fee for this service.</li>
              <li><strong>The right to rectification</strong> – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</li>
              <li><strong>The right to erasure</strong> – You have the right to request that we erase your personal data, under certain conditions.</li>
              <li><strong>The right to restrict processing</strong> – You have the right to request that we restrict the processing of your personal data, under certain conditions.</li>
              <li><strong>The right to object to processing</strong> – You have the right to object to our processing of your personal data, under certain conditions.</li>
              <li><strong>The right to data portability</strong> – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
            </ul>
            <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

            <h3>Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
              <li>By email: {contactEmail}</li>
              <li>By visiting this page on our website: <a href="https://ariversestudio.com/contact">https://ariversestudio.com/contact</a></li>
            </ul>
          </Div>
        </Div>
      </Div>
      <Spacing lg='150' md='80'/>
    </>
  );
}
